// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1) {
  return window['go']['ui']['SessionHandler']['CloseSession'](arg1);
}

export function DetectFormat(arg1) {
  return window['go']['ui']['SessionHandler']['DetectFormat'](arg1);
}

export function GetActiveSession() {
  return window['go']['ui']['SessionHandler']['GetActiveSession']();
}

export function GetSessionInfo(arg1) {
  return window['go']['ui']['SessionHandler']['GetSessionInfo'](arg1);
}

export function ListSessionDirectory(arg1, arg2) {
  return window['go']['ui']['SessionHandler']['ListSessionDirectory'](arg1, arg2);
}

export function LogSessionProvenance(arg1, arg2, arg3, arg4) {
  return window['go']['ui']['SessionHandler']['LogSessionProvenance'](arg1, arg2, arg3, arg4);
}

export function MountSession(arg1, arg2) {
  return window['go']['ui']['SessionHandler']['MountSession'](arg1, arg2);
}

export function OpenSession(arg1) {
  return window['go']['ui']['SessionHandler']['OpenSession'](arg1);
}

export function SelectBestPartition(arg1) {
  return window['go']['ui']['SessionHandler']['SelectBestPartition'](arg1);
}

export function Startup(arg1) {
  return window['go']['ui']['SessionHandler']['Startup'](arg1);
}
