// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListDirectory(arg1) {
  return window['go']['ui']['StorageHandler']['ListDirectory'](arg1);
}

export function MountDisk(arg1) {
  return window['go']['ui']['StorageHandler']['MountDisk'](arg1);
}

export function MountPartition(arg1) {
  return window['go']['ui']['StorageHandler']['MountPartition'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['ui']['StorageHandler']['ReadFile'](arg1);
}

export function ReadFileChunk(arg1, arg2, arg3) {
  return window['go']['ui']['StorageHandler']['ReadFileChunk'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['ui']['StorageHandler']['Startup'](arg1);
}
