// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ui} from '../models';
import {context} from '../models';

export function ListDirectory(arg1:string):Promise<Array<ui.NodeDTO>>;

export function MountDisk(arg1:string):Promise<Array<ui.PartitionDTO>>;

export function MountPartition(arg1:number):Promise<boolean>;

export function ReadFile(arg1:string):Promise<Array<number>>;

export function ReadFileChunk(arg1:string,arg2:number,arg3:number):Promise<Array<number>>;

export function Startup(arg1:context.Context):Promise<void>;
