// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {platform} from '../models';
import {context} from '../models';

export function AddBookmark(arg1:string,arg2:string):Promise<platform.Bookmark>;

export function CancelJob(arg1:string):Promise<boolean>;

export function CloseTab(arg1:number):Promise<void>;

export function ExecuteCapability(arg1:string,arg2:Record<string, any>):Promise<string>;

export function ExecuteUCL(arg1:string):Promise<string>;

export function GetBookmarks():Promise<Array<platform.Bookmark>>;

export function GetJobStatus(arg1:string):Promise<Record<string, any>|boolean>;

export function GetWorkspaceState():Promise<platform.WorkspaceState>;

export function MountDiskTarget(arg1:platform.WorkspaceTarget):Promise<void>;

export function NavigateWorkspace(arg1:string):Promise<void>;

export function OpenTab(arg1:string):Promise<void>;

export function RemoveBookmark(arg1:string):Promise<void>;

export function SetActivePartition(arg1:string):Promise<void>;

export function SetActiveTab(arg1:number):Promise<void>;

export function SetActiveTarget(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UnmountDiskTarget(arg1:string):Promise<void>;
