// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBookmark(arg1, arg2) {
  return window['go']['bridge']['WailsBridge']['AddBookmark'](arg1, arg2);
}

export function CancelJob(arg1) {
  return window['go']['bridge']['WailsBridge']['CancelJob'](arg1);
}

export function CloseTab(arg1) {
  return window['go']['bridge']['WailsBridge']['CloseTab'](arg1);
}

export function ExecuteCapability(arg1, arg2) {
  return window['go']['bridge']['WailsBridge']['ExecuteCapability'](arg1, arg2);
}

export function ExecuteUCL(arg1) {
  return window['go']['bridge']['WailsBridge']['ExecuteUCL'](arg1);
}

export function GetBookmarks() {
  return window['go']['bridge']['WailsBridge']['GetBookmarks']();
}

export function GetJobStatus(arg1) {
  return window['go']['bridge']['WailsBridge']['GetJobStatus'](arg1);
}

export function GetWorkspaceState() {
  return window['go']['bridge']['WailsBridge']['GetWorkspaceState']();
}

export function MountDiskTarget(arg1) {
  return window['go']['bridge']['WailsBridge']['MountDiskTarget'](arg1);
}

export function NavigateWorkspace(arg1) {
  return window['go']['bridge']['WailsBridge']['NavigateWorkspace'](arg1);
}

export function OpenTab(arg1) {
  return window['go']['bridge']['WailsBridge']['OpenTab'](arg1);
}

export function RemoveBookmark(arg1) {
  return window['go']['bridge']['WailsBridge']['RemoveBookmark'](arg1);
}

export function SetActivePartition(arg1) {
  return window['go']['bridge']['WailsBridge']['SetActivePartition'](arg1);
}

export function SetActiveTab(arg1) {
  return window['go']['bridge']['WailsBridge']['SetActiveTab'](arg1);
}

export function SetActiveTarget(arg1) {
  return window['go']['bridge']['WailsBridge']['SetActiveTarget'](arg1);
}

export function Startup(arg1) {
  return window['go']['bridge']['WailsBridge']['Startup'](arg1);
}

export function UnmountDiskTarget(arg1) {
  return window['go']['bridge']['WailsBridge']['UnmountDiskTarget'](arg1);
}
