// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {timeline} from '../models';
import {search} from '../models';
import {api} from '../models';
import {sigma} from '../models';
import {forensic} from '../models';
import {services} from '../models';
import {storage} from '../models';
import {vfs} from '../models';
import {vault} from '../models';
import {context} from '../models';

export function AddFavorite(arg1:string,arg2:string):Promise<void>;

export function AnalyzeFindings(arg1:Array<timeline.TimelineEntry>):Promise<Array<search.Finding>>;

export function BatchHashFiles(arg1:Array<string>):Promise<Array<Record<string, any>>>;

export function BrowseLocalFS(arg1:string):Promise<Array<Record<string, any>>>;

export function BuildUnifiedTimeline(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Record<string, any>>;

export function CancelHashJob(arg1:string):Promise<boolean>;

export function ClearRecentFiles():Promise<void>;

export function Close():Promise<void>;

export function CompareHash(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ExecuteCapability(arg1:string,arg2:string):Promise<string>;

export function ExecuteCommand(arg1:string,arg2:string):Promise<any>;

export function ExecuteSQLQuery(arg1:string):Promise<api.SQLQueryResult>;

export function ExportChainOfCustodyReport(arg1:api.ExportReportRequest):Promise<api.ExportReportResponse>;

export function ExportDiskSummary():Promise<string>;

export function ExportTimelineCSV(arg1:Array<timeline.TimelineEntry>,arg2:string):Promise<void>;

export function ExportTimelineJSON(arg1:Array<timeline.TimelineEntry>,arg2:string):Promise<void>;

export function ExtractFile(arg1:string,arg2:string):Promise<void>;

export function ExtractFileSecure(arg1:string,arg2:string):Promise<void>;

export function GenerateReport(arg1:string,arg2:string,arg3:Array<timeline.TimelineEntry>,arg4:Array<sigma.Alert>,arg5:Array<forensic.ProcessInfo>,arg6:Array<forensic.YaraMatch>):Promise<string>;

export function GetCommandHistory():Promise<Array<services.CommandHistoryEntry>>;

export function GetDetailedDiskInfo():Promise<storage.DiskInfoResponse>;

export function GetDiskHash():Promise<string>;

export function GetDiskInfo():Promise<storage.DiskInfo>;

export function GetEntry(arg1:string):Promise<vfs.Entry>;

export function GetFavorites():Promise<Array<services.FavoriteEntry>>;

export function GetFileInfoForPath(arg1:string):Promise<Record<string, any>>;

export function GetFilePreview(arg1:string):Promise<api.PreviewResponse>;

export function GetGateway():Promise<services.Gateway>;

export function GetGrammarForExtension(arg1:string):Promise<services.GrammarResponse>;

export function GetHashJobStatus(arg1:string):Promise<Record<string, any>>;

export function GetJobStatus(arg1:string):Promise<Record<string, any>>;

export function GetLiveProcesses():Promise<Array<forensic.ProcessInfo>>;

export function GetLocalDrives():Promise<Array<string>>;

export function GetMemorySnapshot():Promise<Record<string, any>>;

export function GetPartitions():Promise<Array<storage.Partition>>;

export function GetRecentFiles():Promise<Array<api.RecentFile>>;

export function GetRegistryArtifacts(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetSigmaRuleCount():Promise<number>;

export function GetSuggestions(arg1:string,arg2:string):Promise<Array<services.Suggestion>>;

export function GetSupportedFormats():Promise<Array<string>>;

export function GetWarnings():Promise<Array<string>>;

export function HashDirectory(arg1:string,arg2:Array<vfs.Entry>):Promise<Record<string, any>>;

export function HashFile(arg1:string,arg2:string):Promise<Record<string, any>>;

export function IngestEvidence(arg1:string,arg2:string,arg3:string,arg4:string):Promise<vault.Manifest>;

export function IngestEvidenceStruct(arg1:api.IngestRequest):Promise<vault.Manifest>;

export function IsDiskOpen():Promise<boolean>;

export function ListCapabilities():Promise<Array<string>>;

export function ListDirectory(arg1:string):Promise<Array<vfs.Entry>>;

export function LoadSigmaRuleDirectory(arg1:string):Promise<number>;

export function LoadTimelineToSQL(arg1:Array<timeline.TimelineEntry>):Promise<number>;

export function LogAnalystAction(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function OpenFile(arg1:string):Promise<storage.OpenResult>;

export function OpenFileDialog():Promise<string>;

export function OpenFileNative(arg1:string,arg2:string):Promise<void>;

export function OpenFileWithPartition(arg1:string,arg2:number):Promise<storage.OpenResult>;

export function ParseCommand(arg1:string,arg2:string):Promise<services.Intent>;

export function ParseEVTXFile(arg1:string):Promise<Record<string, any>>;

export function ParseHiveAndExtractArtifacts(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ParseMFTFile(arg1:string):Promise<Record<string, any>>;

export function PartitionHash(arg1:number):Promise<Record<string, any>>;

export function ReadFile(arg1:string):Promise<Array<number>>;

export function ReadFileChunk(arg1:string,arg2:number,arg3:number):Promise<Array<number>>;

export function RemoveFavorite(arg1:string):Promise<void>;

export function RunMemoryYaraScan(arg1:Array<forensic.ProcessInfo>):Promise<Array<forensic.YaraMatch>>;

export function RunSigmaScan(arg1:Array<timeline.TimelineEntry>):Promise<Array<sigma.Alert>>;

export function SaveReportToFile(arg1:string,arg2:string):Promise<void>;

export function SelectPartition(arg1:number):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartBatchHashJob(arg1:Array<string>):Promise<string>;

export function StartDirectoryHashJob(arg1:string):Promise<string>;

export function StartPartitionHashJob(arg1:number):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function ValidateFile(arg1:string):Promise<storage.ValidationResult>;

export function VerifyCaseIntegrity(arg1:string):Promise<api.VerificationResult>;

export function VerifyEvidenceContainer(arg1:string):Promise<api.VaultResult>;
