// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1, arg2) {
  return window['go']['api']['App']['AddFavorite'](arg1, arg2);
}

export function AnalyzeFindings(arg1) {
  return window['go']['api']['App']['AnalyzeFindings'](arg1);
}

export function BatchHashFiles(arg1) {
  return window['go']['api']['App']['BatchHashFiles'](arg1);
}

export function BrowseLocalFS(arg1) {
  return window['go']['api']['App']['BrowseLocalFS'](arg1);
}

export function BuildUnifiedTimeline(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['api']['App']['BuildUnifiedTimeline'](arg1, arg2, arg3, arg4, arg5);
}

export function CancelHashJob(arg1) {
  return window['go']['api']['App']['CancelHashJob'](arg1);
}

export function ClearRecentFiles() {
  return window['go']['api']['App']['ClearRecentFiles']();
}

export function Close() {
  return window['go']['api']['App']['Close']();
}

export function CompareHash(arg1, arg2) {
  return window['go']['api']['App']['CompareHash'](arg1, arg2);
}

export function ExecuteCapability(arg1, arg2) {
  return window['go']['api']['App']['ExecuteCapability'](arg1, arg2);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['api']['App']['ExecuteCommand'](arg1, arg2);
}

export function ExecuteSQLQuery(arg1) {
  return window['go']['api']['App']['ExecuteSQLQuery'](arg1);
}

export function ExportChainOfCustodyReport(arg1) {
  return window['go']['api']['App']['ExportChainOfCustodyReport'](arg1);
}

export function ExportDiskSummary() {
  return window['go']['api']['App']['ExportDiskSummary']();
}

export function ExportTimelineCSV(arg1, arg2) {
  return window['go']['api']['App']['ExportTimelineCSV'](arg1, arg2);
}

export function ExportTimelineJSON(arg1, arg2) {
  return window['go']['api']['App']['ExportTimelineJSON'](arg1, arg2);
}

export function ExtractFile(arg1, arg2) {
  return window['go']['api']['App']['ExtractFile'](arg1, arg2);
}

export function ExtractFileSecure(arg1, arg2) {
  return window['go']['api']['App']['ExtractFileSecure'](arg1, arg2);
}

export function GenerateReport(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['api']['App']['GenerateReport'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetCommandHistory() {
  return window['go']['api']['App']['GetCommandHistory']();
}

export function GetDetailedDiskInfo() {
  return window['go']['api']['App']['GetDetailedDiskInfo']();
}

export function GetDiskHash() {
  return window['go']['api']['App']['GetDiskHash']();
}

export function GetDiskInfo() {
  return window['go']['api']['App']['GetDiskInfo']();
}

export function GetEntry(arg1) {
  return window['go']['api']['App']['GetEntry'](arg1);
}

export function GetFavorites() {
  return window['go']['api']['App']['GetFavorites']();
}

export function GetFileInfoForPath(arg1) {
  return window['go']['api']['App']['GetFileInfoForPath'](arg1);
}

export function GetFilePreview(arg1) {
  return window['go']['api']['App']['GetFilePreview'](arg1);
}

export function GetGateway() {
  return window['go']['api']['App']['GetGateway']();
}

export function GetGrammarForExtension(arg1) {
  return window['go']['api']['App']['GetGrammarForExtension'](arg1);
}

export function GetHashJobStatus(arg1) {
  return window['go']['api']['App']['GetHashJobStatus'](arg1);
}

export function GetJobStatus(arg1) {
  return window['go']['api']['App']['GetJobStatus'](arg1);
}

export function GetLiveProcesses() {
  return window['go']['api']['App']['GetLiveProcesses']();
}

export function GetLocalDrives() {
  return window['go']['api']['App']['GetLocalDrives']();
}

export function GetMemorySnapshot() {
  return window['go']['api']['App']['GetMemorySnapshot']();
}

export function GetPartitions() {
  return window['go']['api']['App']['GetPartitions']();
}

export function GetRecentFiles() {
  return window['go']['api']['App']['GetRecentFiles']();
}

export function GetRegistryArtifacts(arg1, arg2) {
  return window['go']['api']['App']['GetRegistryArtifacts'](arg1, arg2);
}

export function GetSigmaRuleCount() {
  return window['go']['api']['App']['GetSigmaRuleCount']();
}

export function GetSuggestions(arg1, arg2) {
  return window['go']['api']['App']['GetSuggestions'](arg1, arg2);
}

export function GetSupportedFormats() {
  return window['go']['api']['App']['GetSupportedFormats']();
}

export function GetWarnings() {
  return window['go']['api']['App']['GetWarnings']();
}

export function HashDirectory(arg1, arg2) {
  return window['go']['api']['App']['HashDirectory'](arg1, arg2);
}

export function HashFile(arg1, arg2) {
  return window['go']['api']['App']['HashFile'](arg1, arg2);
}

export function IngestEvidence(arg1, arg2, arg3, arg4) {
  return window['go']['api']['App']['IngestEvidence'](arg1, arg2, arg3, arg4);
}

export function IngestEvidenceStruct(arg1) {
  return window['go']['api']['App']['IngestEvidenceStruct'](arg1);
}

export function IsDiskOpen() {
  return window['go']['api']['App']['IsDiskOpen']();
}

export function ListCapabilities() {
  return window['go']['api']['App']['ListCapabilities']();
}

export function ListDirectory(arg1) {
  return window['go']['api']['App']['ListDirectory'](arg1);
}

export function LoadSigmaRuleDirectory(arg1) {
  return window['go']['api']['App']['LoadSigmaRuleDirectory'](arg1);
}

export function LoadTimelineToSQL(arg1) {
  return window['go']['api']['App']['LoadTimelineToSQL'](arg1);
}

export function LogAnalystAction(arg1, arg2, arg3) {
  return window['go']['api']['App']['LogAnalystAction'](arg1, arg2, arg3);
}

export function OpenFile(arg1) {
  return window['go']['api']['App']['OpenFile'](arg1);
}

export function OpenFileDialog() {
  return window['go']['api']['App']['OpenFileDialog']();
}

export function OpenFileNative(arg1, arg2) {
  return window['go']['api']['App']['OpenFileNative'](arg1, arg2);
}

export function OpenFileWithPartition(arg1, arg2) {
  return window['go']['api']['App']['OpenFileWithPartition'](arg1, arg2);
}

export function ParseCommand(arg1, arg2) {
  return window['go']['api']['App']['ParseCommand'](arg1, arg2);
}

export function ParseEVTXFile(arg1) {
  return window['go']['api']['App']['ParseEVTXFile'](arg1);
}

export function ParseHiveAndExtractArtifacts(arg1, arg2) {
  return window['go']['api']['App']['ParseHiveAndExtractArtifacts'](arg1, arg2);
}

export function ParseMFTFile(arg1) {
  return window['go']['api']['App']['ParseMFTFile'](arg1);
}

export function PartitionHash(arg1) {
  return window['go']['api']['App']['PartitionHash'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['api']['App']['ReadFile'](arg1);
}

export function ReadFileChunk(arg1, arg2, arg3) {
  return window['go']['api']['App']['ReadFileChunk'](arg1, arg2, arg3);
}

export function RemoveFavorite(arg1) {
  return window['go']['api']['App']['RemoveFavorite'](arg1);
}

export function RunMemoryYaraScan(arg1) {
  return window['go']['api']['App']['RunMemoryYaraScan'](arg1);
}

export function RunSigmaScan(arg1) {
  return window['go']['api']['App']['RunSigmaScan'](arg1);
}

export function SaveReportToFile(arg1, arg2) {
  return window['go']['api']['App']['SaveReportToFile'](arg1, arg2);
}

export function SelectPartition(arg1) {
  return window['go']['api']['App']['SelectPartition'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['api']['App']['Shutdown'](arg1);
}

export function StartBatchHashJob(arg1) {
  return window['go']['api']['App']['StartBatchHashJob'](arg1);
}

export function StartDirectoryHashJob(arg1) {
  return window['go']['api']['App']['StartDirectoryHashJob'](arg1);
}

export function StartPartitionHashJob(arg1) {
  return window['go']['api']['App']['StartPartitionHashJob'](arg1);
}

export function Startup(arg1) {
  return window['go']['api']['App']['Startup'](arg1);
}

export function ValidateFile(arg1) {
  return window['go']['api']['App']['ValidateFile'](arg1);
}

export function VerifyCaseIntegrity(arg1) {
  return window['go']['api']['App']['VerifyCaseIntegrity'](arg1);
}

export function VerifyEvidenceContainer(arg1) {
  return window['go']['api']['App']['VerifyEvidenceContainer'](arg1);
}
