// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {storage} from '../models';
import {context} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function DetectFormat(arg1:string):Promise<string>;

export function GetActiveSession():Promise<api.SessionInfo>;

export function GetSessionInfo(arg1:string):Promise<api.SessionInfo>;

export function ListSessionDirectory(arg1:string,arg2:string):Promise<Array<storage.UniversalFileNode>>;

export function LogSessionProvenance(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function MountSession(arg1:string,arg2:string):Promise<api.SessionInfo>;

export function OpenSession(arg1:string):Promise<api.SessionInfo>;

export function SelectBestPartition(arg1:Array<storage.Partition>):Promise<number>;

export function Startup(arg1:context.Context):Promise<void>;
